[package]
name = "markdown2mrkdwn"
version = "0.1.0"
edition = "2021"

[lib]
name = "markdown2mrkdwn"
path = "src/lib.rs"

[dependencies]
markdown = "1.0.0-alpha.14"
serde_json = { version = "1.0.107", features = [] }
